=== alkacon/opencms-core/src/org/opencms/configuration/opencms-vfs.dtd
<!-- 
# The root configuration node is called <opencms> for all OpenCms configurations.
-->
<!ELEMENT opencms (vfs)>

<!--
# <vfs> configuration:
#
# The configuration of the 'virtual file system' is done here.
-->

<!ELEMENT vfs (
	resources,
	defaultfiles,
	translations?, 
	online-folders?,
	xmlcontent?)>

<!ELEMENT resources (
	resourceloaders, 
	resourcetypes,
	collectors?,
	namegenerator?,
	mimetypes?,
	relationtypes?,
	html-converters?)>

<!ELEMENT resourceloaders (loader+)>
<!ELEMENT loader (param*)>
<!ATTLIST loader class CDATA #REQUIRED>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED>

<!--
# Relation types configuration.
#
# This node defines new relation types that could be used by the API 
# to complement the internal system defined relation types.
#
# A relation type has a name which should only contain (uppercase) letters, numbers and underscores.
# (if you want to localize the name you can define a GUI_RELATIONTYPE_ localization key)
# and a type which may be weak or strong, strong related resources will be published together.
-->
<!ELEMENT relationtypes (relationtype*)>
<!ELEMENT relationtype EMPTY>
<!ATTLIST relationtype name CDATA #REQUIRED type CDATA #REQUIRED>

<!--
# Collectors for gathering Lists of resources from the VFS.	
-->
<!ELEMENT collectors (collector+)>
<!ELEMENT collector EMPTY>
<!ATTLIST collector class CDATA #REQUIRED order CDATA #REQUIRED>


<!-- 
  URL name generator class for XML contents. 
-->
<!ELEMENT namegenerator EMPTY>
<!ATTLIST namegenerator class CDATA #REQUIRED>

<!--
# MIME type configuration.
#
# This is a simple list of "extension" and "type" attributes.
-->
<!ELEMENT mimetypes (mimetype*)>
<!ELEMENT mimetype EMPTY>
<!ATTLIST mimetype extension CDATA #REQUIRED type CDATA #REQUIRED>

<!--
# HTML converters manipulate the content of pages containing HTML values.
# The behavior of the HTML converters is configured by using the "content-conversion"
# property value. The name(s) entered here are passed to the matching HTML converter. 
# There can be entered more than one option in the property, e.g. "cleanup;xhtml",
# the ";" acts as separator.
-->
<!ELEMENT html-converters (html-converter*)>
<!ELEMENT html-converter EMPTY>
<!ATTLIST html-converter name CDATA #REQUIRED class CDATA #REQUIRED>

<!--
# Default file names for directories.
#
# These are the default files that are read when a folder name 
# is requested by the user in a http request.
-->
<!ELEMENT defaultfiles (defaultfile+)>
<!ELEMENT defaultfile EMPTY>
<!ATTLIST defaultfile name CDATA #REQUIRED>

<!--
# Translations for file and folder names.
-->
<!ELEMENT translations (filetranslations?, foldertranslations?, xsdtranslations?)>
<!ELEMENT translation (#PCDATA)>

<!ELEMENT online-folders (path*, param*)>
<!ELEMENT path (#PCDATA)>

<!--
# Filename translation is used when creating new files to automatically 
# replace chars not allowed in the OpenCms VFS into allowed ones.
# This is done using Perl5 regular search & replace expression translation rules.
# One of the most important uses is e.g. replacement of space with "_".
# So if a user uploads a file "my file.txt" the name will be translated to "my_file.txt".
# All of the translation rules are applied to the filename in the given order.
#
# By setting the "enabled" attibute to "false" you can disable filename translation.
# It is enabled by default. It's recommended to leave this enabled.
#
# Filename translation is only applied to: 
#   - File uploads (the name of the uploaded file is translated)
#   - Zip-File uploads (all filenames in the Zip are translated)
-->

<!ELEMENT filetranslations (translation*)>
<!ATTLIST filetranslations enabled (TRUE|true|FALSE|false) #REQUIRED>

<!--
# Folder translation can be used to maintain compatibility with older
# OpenCms installations, e.g. with version before the 5.0 (beta 2) release.
# This is done using Perl5 regular search & replace expression rules.
# All read and write access to a OpenCms VFS folder that matches one of given
# translation rules is automatically translated to the new name.
# Translation is stopped after the first match was found.
#
# The attribute "enabled" controls if folder translation is enabled.
# The default is "not enabled". Use this feature only if you have specific 
# reasons because it might hurt performance.
-->

<!ELEMENT foldertranslations (translation*)>
<!ATTLIST foldertranslations enabled (TRUE|true|FALSE|false) #REQUIRED>

<!--
# XSD (XML schema) translation can be used to find XSD files that have been 
# moved from their original location. Since the XSD path is stored in the XML,
# and the CRE can not be used here, existing XML files that point to a moved
# XSD would not be able to find the schema. Using the translation, the schema
# can still be found without updating all the affected XML files.
# This is done using Perl5 regular search & replace expression rules.
# All read and write access to a OpenCms XSD schema that matches one of given
# translation rules is automatically translated to the new name.
# Translation is stopped after the first match was found.
#
# The attribute "enabled" controls if folder translation is enabled.
# The default is "not enabled".
-->

<!ELEMENT xsdtranslations (translation*)>
<!ATTLIST xsdtranslations enabled (TRUE|true|FALSE|false) #REQUIRED>

<!--
# XML content definitions that are used to build XML content items.
#
# The configured widget classes must implement the interface 
# "org.openmcms.workplace.xmlwidgets.I_CmsXmlWidget".
#
# Each XML content schema type configuration requires a class that implements
# the interface "org.opencms.xml.types.I_CmsXmlSchemaType". This type defines 
# the basic behaviour of the XML content item data. For creating the 
# XML content editor, a default widget class must be given that implements the 
# interface "org.opencms.workplace.xmltypes.I_CmsXmlWidget". 
# The configured widget class must also be listed in the "widgets" node.
# For a widget, an optional alias name can be configured as well as a default
# widget configuration that is used to define the widget behavior in the structured
# content editor if no individual configuration is defined in the XSD for the XML content.
# Additional widget aliases can be defined using the widget-alias subelement. 
-->
<!ELEMENT xmlcontent (widgets, schematypes)>

<!ELEMENT widgets (widget*)>
<!ELEMENT widget (widget-alias*)>
<!ATTLIST widget class CDATA #REQUIRED alias CDATA #IMPLIED configuration CDATA #IMPLIED>

<!ELEMENT widget-alias (#PCDATA)>

<!ELEMENT schematypes (schematype*)>
<!ELEMENT schematype EMPTY>
<!ATTLIST schematype class CDATA #REQUIRED defaultwidget CDATA #REQUIRED>

<!--
# Name for the property node (see below), this node already exists in opencms-modules.xml
-->
<!ELEMENT name (#PCDATA)>

<!--
# Include the resource types DTD.
-->
<!ENTITY % opencms-resourcetypes SYSTEM "http://www.opencms.org/dtd/6.0/opencms-resourcetypes.dtd"> 
%opencms-resourcetypes;

=== alkacon/opencms-core/webapp/WEB-INF/config/opencms-vfs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.opencms.org/dtd/6.0/opencms-vfs.dtd">

<opencms>
    <vfs>
        <resources>
            <resourceloaders>
                <loader class="org.opencms.loader.CmsDumpLoader" />
                <loader class="org.opencms.loader.CmsImageLoader">
                    <param name="image.scaling.enabled">true</param>
                    <param name="image.scaling.concurrency">6</param>
                </loader>
                <loader class="org.opencms.loader.CmsPointerLoader" />
                <loader class="org.opencms.loader.CmsJspLoader">
                    <param name="taglib.cms">http://www.opencms.org/taglib/cms</param>
                    <param name="taglib.c">http://java.sun.com/jsp/jstl/core</param>
                    <param name="taglib.fn">http://java.sun.com/jsp/jstl/functions</param>
                    <param name="taglib.fmt">http://java.sun.com/jsp/jstl/fmt</param>
                    <param name="taglib.x">http://java.sun.com/jsp/jstl/xml</param>
                    <param name="taglib.sql">http://java.sun.com/jsp/jstl/sql</param>
                </loader>
                <loader class="org.opencms.loader.CmsXmlPageLoader" />
                <loader class="org.opencms.loader.CmsXmlContentLoader" />
                <loader class="org.opencms.loader.CmsXmlContainerPageLoader" />
                <loader class="org.opencms.loader.CmsRedirectLoader" />
                <loader class="org.opencms.loader.CmsSeoFileLoader" />
                <loader class="org.opencms.loader.CmsMacroFormatterLoader" />
            </resourceloaders>
            <resourcetypes>
                <type class="org.opencms.file.types.CmsResourceTypeUnknownFolder" name="unknown_folder" id="-2" />
                <type class="org.opencms.file.types.CmsResourceTypeUnknownFile" name="unknown_file" id="-1" />
                <type class="org.opencms.file.types.CmsResourceTypeFolder" name="folder" id="0">
                    <param name="restypes.indexpage">none|xmlpage|layoutpage</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypePlain" name="plain" id="1">
                    <mappings>
                        <mapping suffix=".txt" />
                        <mapping suffix=".html" />
                        <mapping suffix=".htm" />
                        <mapping suffix=".java" />
                        <mapping suffix=".js" />
                        <mapping suffix=".xhtml" />
                        <mapping suffix=".txt" />
                        <mapping suffix=".xml" />
                        <mapping suffix=".xsd" />
                        <mapping suffix=".css" />
                        <mapping suffix=".map" />
                        <mapping suffix=".woff" />
                        <mapping suffix=".woff2" />
                        <mapping suffix=".eot" />
                        <mapping suffix=".otf" />
                        <mapping suffix=".ttc" />
                        <mapping suffix=".ttf" />
                        <mapping suffix=".csv" />
                    </mappings>
                    <param name="gallery.type.names">downloadgallery</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypeBinary" name="binary" id="2">
                    <mappings>
                        <mapping suffix=".pdf" />
                        <mapping suffix=".zip" />
                        <mapping suffix=".7z" />
                        <mapping suffix=".class" />
                        <mapping suffix=".ppt" />
                        <mapping suffix=".doc" />
                        <mapping suffix=".docx" />
                        <mapping suffix=".xlsx" />
                        <mapping suffix=".pptx" />
                        <mapping suffix=".xls" />
                        <mapping suffix=".jar" />
                        <mapping suffix=".flv" />
                        <mapping suffix=".swf" />
                        <mapping suffix=".mp4" />
                        <mapping suffix=".ogv" />
                        <mapping suffix=".webm" />
                        <mapping suffix=".rar" />
                        <mapping suffix=".odt" />
                        <mapping suffix=".odp" />
                        <mapping suffix=".mp3" />
                        <mapping suffix=".m4a" />
                        <mapping suffix=".aac" />
                        <mapping suffix=".oga" />
                        <mapping suffix=".ogg" />
                        <mapping suffix=".m4v" />
                        <mapping suffix=".wmv" />
                        <mapping suffix=".mpeg" />
                        <mapping suffix=".mpg" />
                        <mapping suffix=".mov" />
                        <mapping suffix=".qt" />
                        <mapping suffix=".avi" />
                        <mapping suffix=".pkpass" />
                        <mapping suffix=".ai" />
                    </mappings>
                    <param name="gallery.type.names">downloadgallery</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypeImage" name="image" id="3">
                    <mappings>
                        <mapping suffix=".jpeg" />
                        <mapping suffix=".jpg" />
                        <mapping suffix=".gif" />
                        <mapping suffix=".png" />
                        <mapping suffix=".tif" />
                        <mapping suffix=".tiff" />
                        <mapping suffix=".svg" />
                        <mapping suffix=".webp" />
                    </mappings>
                    <param name="gallery.type.names">imagegallery|downloadgallery</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypeJsp" name="jsp" id="4">
                    <mappings>
                        <mapping suffix=".jsp" />
                    </mappings>
                    <properties>
                        <property>
                            <name>export</name>
                            <value type="shared"><![CDATA[false]]></value>
                        </property>
                    </properties>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypePointer" name="pointer" id="5">
                    <param name="gallery.type.names">linkgallery</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypeXmlContent" name="xmlcontent" id="7">
                    <param name="gallery.type.names">downloadgallery</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypeFolderExtended" name="imagegallery" id="8">
                    <param name="folder.class">org.opencms.workplace.galleries.CmsAjaxImageGallery</param>
                    <param name="folder.class.params">w:120,h:90,c:D4D0C8,t:1,r:2</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypeFolderExtended" name="downloadgallery" id="9">
                    <param name="folder.class">org.opencms.workplace.galleries.CmsAjaxDownloadGallery</param>
                </type>
                <type class="org.opencms.file.types.CmsResourceTypeFolderExtended" name="linkgallery" id="10">
                    <param name="folder.class">org.opencms.workplace.galleries.CmsAjaxLinkGallery</param>
                </type>
            </resourcetypes>
            <collectors>
                <collector class="org.opencms.file.collectors.CmsPriorityResourceCollector" order="100" />
                <collector class="org.opencms.file.collectors.CmsDefaultResourceCollector" order="110" />
                <collector class="org.opencms.file.collectors.CmsDateResourceCollector" order="120" />
                <collector class="org.opencms.file.collectors.CmsTimeFrameCategoryCollector" order="130" />
                <collector class="org.opencms.file.collectors.CmsCategoryResourceCollector" order="140" />
                <collector class="org.opencms.file.collectors.CmsSubscriptionCollector" order="150" />
                <collector class="org.opencms.file.collectors.CmsChangedResourceCollector" order="160" />
                <collector class="org.opencms.file.collectors.CmsSolrCollector" order="170" />
            </collectors>

            <mimetypes>

                <!--
                    # The basic list of mimetypes was taken from HTML 5 boilerplate project.
                    # See https://github.com/h5bp/server-configs/.
                    # Apparently the h5pb lists differ per server, this was taken from Nginx.
                    # Extensions have been added for office formats and Microsoft related files.
                -->

                <!-- Data interchange -->
                <mimetype extension=".atom" type="application/atom+xml" />
                <mimetype extension=".json" type="application/json" />
                <mimetype extension=".map" type="application/json" />
                <mimetype extension=".topojson" type="application/json" />
                <mimetype extension=".jsonld" type="application/ld+json" />
                <mimetype extension=".rss" type="application/rss+xml" />
                <mimetype extension=".geojson" type="application/vnd.geo+json" />
                <mimetype extension=".rdf" type="application/xml" />
                <mimetype extension=".xml" type="application/xml" />

                <!-- JavaScript -->
                <mimetype extension=".js" type="text/javascript" />
                <mimetype extension=".mjs" type="text/javascript" />
                <mimetype extension=".wasm" type="application/wasm" />

                <!-- Manifest files -->
                <mimetype extension=".webapp" type="application/x-web-app-manifest+json" />
